---
# Name: Install and configure a basic Dovecot installation

- name: Install Dovecot
  apt: 
    name:
      - dovecot-core
    state: latest

- name: Install Dovecot plugins
  apt:
    name:
      - dovecot-imapd
      - dovecot-ldap

      # Future plugins
      # - dovecot-sieve - Allow user mail filters
      # - dovecot-managesieved - Ease management of said filters
      # - dovecot-pop3d - Probably unneeded
    state: latest

# To be enabled when we move to Debian 10.
#- name: Install a strong 4096-bit Diffie-Hellman group file
#  copy:
#    src: dh.pem
#    dest: /etc/dovecot/dh.pem
#    owner: root
#    group: root
#    mode: '0644'

- name: Configure Dovecot settings
  template:
    src: conf.d/{{ item }}.j2
    dest: /etc/dovecot/conf.d/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - 10-mail.conf
    - 10-ssl.conf
    - 10-auth.conf
    - 10-master.conf
  notify: restart Dovecot
