---
# file: site.yml
- hosts: web_servers
  remote_user: '{{ glass_user }}'
  become: yes

  tasks:
  #role:mail-mta
  - name: Install MTA-relevant packages
    apt: name={{ item }} state=latest
    with_items:
      - mutt
      - swaks

  - name: Install exim4
    apt: name=exim4-daemon-light

  - name: Preconfigure exim4
    template:
      src: mail-mta/update-exim4.conf.conf.j2
      dest: /etc/exim4/update-exim4.conf.conf
      owner: root
      group: root
      mode: 0644
    notify: "update exim4 config"

  #role:mailman
  - name: Mailman - Install Mailman and fcgiwrap
    apt: name={{ item }} state=latest
    with_items:
      - mailman
      - fcgiwrap

  - name: Mailman - Configure mailman URLs
    template:
      src: mailman/mm_cfg.py.j2
      dest: /etc/mailman/mm_cfg.py
    notify: reload mailman

  - name: Mailman - Install nginx site config
    template:
      src: mailman/lists.plug.org.au.conf
      dest: /etc/nginx/sites-available/lists.plug.org.au.conf
    notify: reload nginx

  - name: Mailman - Enable nginx site config
    file:
      state: link
      src: ../sites-available/lists.plug.org.au.conf
      dest: /etc/nginx/sites-enabled/lists.plug.org.au.conf
    notify: reload nginx

  #TODO: Move this to its own file
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded

    - name: reload mailman
      service: name=mailman state=reloaded

    - name: reconfigure exim4
      command: dpkg-reconfigure -f noninteractive exim4-config
      listen: "update exim4 config"

    - name: restart exim4
      service: name=exim4 state=restarted
      listen: "update exim4 config"
