---
# file: site.yml
- hosts: web_servers
  remote_user: '{{ glass_user }}'
  become: yes

  roles:
    - base
    - dns-server
    - letsencrypt
    - borgbackup
    - plug-website

  tasks:
  #role:ldap
  - name: Install LDAP server
    apt: name=slapd state=latest

  - name: Install useful LDAP utils
    apt: name=ldap-utils state=latest

  - name: Create LDAP automatic backup script
    template:
      src: ldap/20-ldapdump
      dest: /etc/cron.daily/20-ldapdump
      owner: root
      group: root
      mode: 0755

  - name: Create directory to house LDAP backups
    file:
      path: /var/backups/slapd
      state: directory
      owner: root
      group: root
      mode: 0700
      recurse: yes

  #role:php
  - name: PHP - Install php-fpm
    apt: name=php-fpm
    # TODO Configure php-fpm

  #role:ugmm
  - name: UGMM - Install smarty3 templating engine
    apt: name=smarty3 state=latest

  - name: UGMM - Install LDAP PHP module
    apt: name=php-ldap state=latest
    # TODO nginx cofig
    # TODO php pool?

  #role:fail2ban
  - import_role: name=fail2ban

  #role:mumble-servers
  - name: Install Mumble
    apt: name=mumble-server state=latest

  - name: Set mumble SSL
    # https://stackoverflow.com/questions/24334115/ansible-lineinfile-for-several-lines
    lineinfile:
      name: /etc/mumble-server.ini
      regexp: "^#? *{{ item.key | regex_escape() }}="
      line: "{{ item.key }}={{ item.value }}"
    with_dict:
      'sslCert': '/etc/letsencrypt/live/plug.org.au/fullchain.pem'
      'sslKey': '/etc/letsencrypt/live/plug.org.au/privkey.pem'
    notify: restart mumble-server

  #role:icecast
  - import_role: name=icecast

  #role:mailman
  - import_role: name=mailman2

  #TODO: Move this to its own file
  handlers:
    - name: restart mumble-server
      service: name=mumble-server state=restarted

- import_playbook: mail_servers.yml
