---
# file: site.yml
- hosts: web_servers
  remote_user: '{{ glass_user }}'
  become: yes

  roles:
    - base
    - dns-server
    - letsencrypt
    - borgbackup
    - plug-website
    - ldap-server
    - ugmm
    - fail2ban
    - mumble-server
    - icecast
    - mailman2

- import_playbook: mail_servers.yml
