---
# Name: Install and configure Let's Encrypt Certbot for nginx

- name: Install Certbot + nginx plugin
  apt: 
    name:
      - certbot
      - python-certbot-nginx
    state: latest

- name: certbot hook, reload nginx
  lineinfile:
    dest: /etc/letsencrypt/cli.ini
    content: 'deploy-hook = systemctl reload nginx'
