---
# Name: Install and configure OpenDKIM

- name: Install OpenDKIM + associated tools
  apt:
    name:
      - opendkim
      - opendkim-tools
    state: latest

- name: Install DKIM private keys
  copy:
    src: secrets/dkimkeys/{{ item }}
    dest: /etc/dkimkeys/{{ item }}
    owner: root
    group: opendkim
    mode: '0640'
  loop:
    - iec-2025-test.private
    - iec2025.private

- name: Create socket directory
  file:
    path: /var/spool/postfix/opendkim
    state: directory
    owner: opendkim
    group: opendkim
    mode: '0710'

- name: Configure OpenDKIM
  template:
    src: opendkim.conf.j2
    dest: /etc/opendkim.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload opendkim

- name: OpenDKIM - Configure key table
  template:
    src: keytable.j2
    dest: /etc/dkimkeys/keytable
    owner: root
    group: opendkim
    mode: '0644'
  notify: reload opendkim

- name: OpenDKIM - Configure signing table
  template:
    src: signingtable.j2
    dest: /etc/dkimkeys/signingtable
    owner: root
    group: opendkim
    mode: '0644'
  notify: reload opendkim

- name: OpenDKIM - Configure trusted hosts
  template:
    src: trustedhosts.j2
    dest: /etc/dkimkeys/trustedhosts
    owner: root
    group: opendkim
    mode: '0644'
  notify: reload opendkim

- name: Add postfix user to opendkim group
  user:
    name: postfix
    groups: opendkim
    append: yes
