- name: Install Mumble
  apt: name=mumble-server state=latest

- name: Set mumble SSL
  # https://stackoverflow.com/questions/24334115/ansible-lineinfile-for-several-lines
  lineinfile:
    name: /etc/mumble-server.ini
    regexp: "^#? *{{ item.key | regex_escape() }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict:
    'sslCert': '/etc/letsencrypt/live/plug.org.au/fullchain.pem'
    'sslKey': '/etc/letsencrypt/live/plug.org.au/privkey.pem'
  notify: restart mumble-server
