---
# Name: Install and configure SpamAssassin

- name: Install SpamAssassin and spamc
  apt: 
    name:
      - spamassassin
      - spamc
    state: latest

- name: Configure SpamAssassin
  template:
    src: local.cf.j2
    dest: /etc/spamassassin/local.cf
    owner: root
    group: root
    mode: '0644'

- name: Configure SpamAssassin default settings
  template:
    src: spamassassin-default.j2
    dest: /etc/default/spamassassin
    owner: root
    group: root
    mode: '0644'

- name: Enable and start SpamAssassin service
  systemd:
    name: spamassassin
    enabled: yes
    state: started
