- name: Install Hugo
  apt: name=hugo state=latest

- name: Use Git to checkout latest plug website
  git: version="master" repo="https://github.com/plugorgau/plugorgau.github.io.git" dest="/home/glass/plugorgau.github.io/"
  become_user: glass
  register: plug_website_git

- name: Use Hugo to build plug website
  # XXX: temporarily use a non-packaged copy of hugo to build the site
  shell: "/home/glass/.local/bin/hugo -d ./_site"
  args:
    chdir: /home/glass/plugorgau.github.io/
  become_user: glass
  when: plug_website_git.changed
  register: plug_website_new_build

- name: Use rsync + a script to destructively update running site
  shell: bash /home/glass/plugorgau.github.io/deploy.sh
  when: plug_website_new_build.changed

#- name: Use rsync destructively to update running site
#  synchronize:
#    src: /home/glass/plugorgau.github.io/_site/
#    dest: /var/www/bayonet.plug.org.au/
#    delete: yes
#    recursive: yes
#  become_user: www-data
#  when: plug_website_new_build.changed

- name: Website - install nginx redirect map
  template:
    src: redirects.map
    dest: /etc/nginx/redirects.map
  notify: reload nginx

- name: Install nginx site config
  template:
    src: plug.org.au.conf
    dest: /etc/nginx/sites-available/plug.org.au.conf
  notify: reload nginx

- name: Enable nginx site config
  file:
    state: link
    src: ../sites-available/plug.org.au.conf
    dest: /etc/nginx/sites-enabled/plug.org.au.conf
  notify: reload nginx
