---
# Name: Install and configure SpamAssassin

- name: Install SpamAssassin, spamc, and spamass-milter
  apt:
    name:
      - spamassassin
      - spamc
      - spamass-milter
    state: latest

- name: Configure SpamAssassin
  template:
    src: local.cf.j2
    dest: /etc/spamassassin/local.cf
    owner: root
    group: root
    mode: '0644'

- name: Enable SpamAssassin nightly cron
  lineinfile:
    dest: /etc/default/spamassassin
    create: true
    regexp: '^CRON='
    line: CRON=1

- name: Run spamd unprivileged
  lineinfile:
    dest: /etc/default/spamd
    regexp: '^OPTIONS='
    line: 'OPTIONS="-u debian-spamd --nouser-config --create-prefs --max-children 5 --helper-home-dir"'

- name: Enable and start SpamAssassin service
  systemd:
    name: spamd
    enabled: yes
    state: started
